# Find Eigendecomposition of A matrix

In [1]:
import numpy as np
import numpy.random as nr
import matplotlib.pyplot as plt
from itertools import combinations
%matplotlib inline

## Create a small array  
A = np.array([[1,3], [3, 1]])
A

array([[1, 3],
       [3, 1]])

In [2]:
## Eigendecomposition
## Complete the code below
Q = np.transpose(Q)
## Complete the code below
print(Eigs)
print(Q)

[[ 4.  0.]
 [ 0. -2.]]
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]


Examine the result and answer the question.

1. Explain what is Eigendecomposition
2. What is the equation of Eigendecomposition
3. How many is/are eigenvalues? What is/are their values?

**Answers:** 
 ##Insert the answers below